/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2019-03-12 11:12:54 
*/
import { InterfaceDeclaration } from "typescript";

export interface IEmptyClass {
    p: string;
    jo(stringi: string, callback: () => void): void;
    opt(stringi: string, opti?: number): void;
}
