/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2019-03-12 11:00:49 
*/

import { InterfaceDeclaration } from "typescript";
import { IEmptyInterface } from "./IEmptyInterface";
import { EmptyClass } from "./Class2";
